### ISSUE TITLE
Batch collapse and expand menus by function method

### ISSUE THREAD

**Issue by jahnli** [TuSimple/naive-ui#1536]
### This function solves the problem (这个功能解决的问题)
Batch collapse and expand menus by function method
### Expected API (期望的 API)
Batch collapse and expand menus by function method

**Comment by 07akioni** [comment]
@Talljack use watcheffect to initilize the uncontrolledExpandedKeys

**Comment by jahnli** [comment]
@07akioni  Are you considering similar control functions like iView and Ant

**Comment by Talljack** [comment]
> @Talljack use watcheffect to initilize the uncontrolledExpandedKeys

OK

**Comment by 07akioni** [comment]
> @07akioni Are you considering similar control functions like iView and Ant

No, if you reset `default-value` to `[]`, the collapsed state would be reset.

However with the new implementation, there would be some problems if user is writing `<n-collapse :default-value="[]" />` since every times the component rerenders, watchEffect would be executed again. So I may add `watch-default` prop later.

**Comment by 07akioni** [comment]
@Talljack 我想了一下这么做有点问题就是如果用户写了 `<n-menu :default-expanded-keys="[]" />` 的话每次重新渲染都会触发 watchEffect，这样也有点小问题，所以在 watchEffect 要检查两次的数组是不是包含的值没变化。

**Comment by 07akioni** [comment]
新增了一个 `watch-props` 的属性解决了

**Comment by jahnli** [comment]
@07akioni  Is it possible to provide demo in the document for everyone's reference
