### ISSUE TITLE
Improve icon integration

### ISSUE THREAD

**Issue by hspaay** [TuSimple/naive-ui#1829]
### This function solves the problem (这个功能解决的问题)
The use of icons in buttons and menu's is not very elegant and a lot of work. For example:
To add an icon to a button, a template slot must be used, that contains an NIcon, that wraps an icon component, like this: 
```
<NButton>
  <template #icon>
    <NIcon>
      <LinkOutlined/>
    </NIcon>
 </template
</NButton>
```
That is 7 lines for every icon. This adds a mental load reading code. Instead of seeing, 'icon=...' that simply expresses the intent to show an icon, there is all this code to read. This is what I mean with not very elegant.

Similarly, Showing an icon in a Dropdown, the docs recommend adding renderIcon function to the 'icon' field in the menu items. This too is cumbersome and distracting.  

### Expected API (期望的 API)
The proposed usage is to simply specify the icon component:
```
<NButton :icon="LinkOutlined" />
```
and for Dropdowns the item would contain a field {icon: LinkOutlined}

This minimizes the mental load in understanding the intent and is very elegant due to its simplicity.

**Comment by 07akioni** [comment]
For the first case, you can use

```vue
<n-button #icon>
  <n-icon>
    <link-outlined />
  </n-icon>
</n-button>
```

**Comment by hspaay** [comment]
Yes maintenance is always a concern. It would be nice if we would not be bound to this restriction.

I would like to offer the thought that fewer artifacts in the code makes it more readable for the user. After 25 years in development I've come to appreciate simplicity code. It looks like we have a different perspective on this.

Thank you kindly for taking the time to reply and for your efforts on naive-ui. I wish you good luck with this library.

**Comment by 07akioni** [comment]
I fact we have similar thoughts, but we are playing different roles.

As a library developer I want to achieve the balance between userland code and library code. I've seem tons of rubbish library code in company since they only care about putting things in. Few of them care about if a library is maintainable, and as a result both users and maintainer suffers.

As a user I do want a library can expose a clean API that it can so that I can focusing on my own purpose.

However when it comes to reality, more concerns happens. Some the resource is limited, we can't just putting everything in the library.

**Comment by hspaay** [comment]
Well put @07akioni, reality has the last word :+1:

**Comment by cardosofelipe** [comment]
Hello, I would like to  bump this feature request, this would be a great improvement over the current  implementation.  Maybe you could make a specific component:  NIconButton.
Could be something simple which accepts only an icon and renders a button with one-liner:
<NIconButton  :icon="LinkOutlined"/>
Or something like that.
