### ISSUE TITLE
[Form Item] The color of the success "validation-status" is not changed

### ISSUE THREAD

**Issue by cefiro** [TuSimple/naive-ui#2841]
### TuSimple/naive-ui version (版本)
2.28.2

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
100.0.4896.127

### System and its version (系统及其版本)
Linux

### Reappearance link (重现链接)
https://codesandbox.io/s/goofy-volhard-wqrj16?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Set the validation-status="success" property for the NFormItem component

### Expected results (期望的结果)
Green color is expected

### Actual results (实际的结果)
The color does not change

**Comment by 07akioni** [comment]
This is expected, success won't have any different. It's provided so that you can override default validation status.

**Comment by TrayserCassa** [comment]
I currently stepped over this and was also excepted a green color because the default is undefined. Why I want to show a green validation:

If the user wants to create a instance in our infrastructure we check if the name is valid. So If the User is entering a name this will be check directly and I wanted to show them, yes this name is ok. I think it's not really necessary because, 'hey this is not valid' is working good enough for checking. But I saw the success and find it kind of cool.
