### ISSUE TITLE
n-input: vertical padding theme override not working

### ISSUE THREAD

**Issue by OrbisK** [TuSimple/naive-ui#3313]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Opera GX core: 88.0.4412.85

### System and its version (系统及其版本)
Win 11

### Reappearance link (重现链接)
https://codesandbox.io/s/jolly-feather-ismx1c?file=/src/App.vue

### Reappearance steps (重现步骤)
see reprod.

### Expected results (期望的结果)
apply x and y padding

### Actual results (实际的结果)
y padding is missing

**Comment by Draeston** [comment]
It appears also in InternalSelection

**Comment by Draeston** [comment]
And maybe in Date Picker and other input elements

**Comment by 07akioni** [comment]
This is by design.

Since input has a height config, if padding top & bottom is configurable it would conflict with height. So only height will be applied. If you need you should use height like this.

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/18677354/179813910-940fa1ae-4c15-4d70-a448-440d84832134.png">
