### ISSUE TITLE
Make tabs work without tab-pane

### ISSUE THREAD

**Issue by 07akioni** [TuSimple/naive-ui#809]
### This function solves the problem (这个功能解决的问题)
Only use the bar
### Expected API (期望的 API)
```
<n-tabs>
  <n-tab name="123">123</n-tab>
  <n-tab name="456">456</n-tab>
</n-tabs>
```

**Comment by moolex** [comment]
Current (2.26.1) n-tabs can't works without n-tab-pane, if tab-pane generated from array, in tab it must check array length first, otherwise it will show error with "Cannot read properties of undefined (reading 'props'), Tabs.js:53:40 flatten(slots.default())[0].props.name"

That means we can't use card tab with addable props but without any panes

Expected API

```
<n-tabs type="card" addable>
  <n-tab-pane v-for="item in items" :key="item.id" :name="item.name">
    Some content
  </n-tab-pane>
</n-tabs>
```

**Comment by 07akioni** [comment]
> ns we can't use card tab with addable props but

https://www.naiveui.com/zh-CN/os-theme/components/tabs#no-pane.vue

It doesn't work?

**Comment by moolex** [comment]
https://codesandbox.io/s/fast-glade-ec1ted?file=/src/App.vue

It works with <n-tabs /> or static pane in tab but not dynamic panes from array

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/fast-glade-ec1ted?file=/src/App.vue
> 
> It works with self-closing n-tabs or static pane in tab but not dynamic panes from array

The main problem is that `n-tabs` assume` there's at least one child.
