### ISSUE TITLE
Icons in horizontal menu children do not respond to being clicked

### ISSUE THREAD

**Issue by spenserblack** [TuSimple/naive-ui#823]
### TuSimple/naive-ui version (版本)
2.16.2

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
Chromium(Version 92.0.4515.131 (Official Build) snap (64-bit))

### System and its version (系统及其版本)
Ubuntu 20.04.2 LTS

### Node version (Node 版本)
16.6.1

### Reappearance link (重现链接)
https://github.com/spenserblack/n-menu-router-issue-example

### Reappearance steps (重现步骤)
1. Switch mode to `horizontal`
2. Expand collapsed submenu
3. Click icon
4. See menu option is highlighted, but route does not change

### Expected results (期望的结果)
Same behavior as vertical mode. If icon is clicked, it should act like label is clicked.

### Actual results (实际的结果)
Only label properly responds to being clicked in horizontal mode.

**Comment by Volankey** [comment]
In fact, if you click precisely to the `<a/>`, it can switch the route.
In vertical mode, you can click on other areas to switch routing because we wrote the following css code:
![image](https://user-images.githubusercontent.com/23287363/128821587-6808ee52-c785-4fd7-9441-a586450303fb.png)
`<a /> `has` &::before`, it covers the entire menu-item. But in horizontal there not have it.

Do we need to add such css to the dropdown of the menu? @07akioni

**Comment by 07akioni** [comment]
@Volankey Add it to `n-dropdown`
